language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database ifindtest;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD null;" -U postgres
  - npm install -g sequelize-cli
script:
  - npm test
after_success:
  - npm run coverage