language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test
  - SECRET_KEY="travissecretkey"
  - TEST_DB=ifindtest
  - DB_USER=test_user
  - DB_PASS=password

before_script:
  - psql -c 'create database ifindtest;' -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD password;" -U postgres
  - npm install -g sequelize-cli
script:
  - npm test
after_success:
  - npm run coverage