language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test
  - SECRET_KEY="travissecretkey"
  - TEST_DB=ifindtest
  - DB_USER=postgres
  - ADMIN_FIRSTNAME="guy"
  - ADMIN_LASTNAME="one"
  - ADMIN_EMAIL="guyone@guys.com"
  - ADMIN_PHONENUMBER="0991807268"


before_script:
  - psql -c 'create database ifindtest;' -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD null;" -U postgres
  - npm install -g sequelize-cli
script:
  - npm test
after_success:
  - npm run coverage